[package]
name = "rafflesia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swrs = { path = "../swrs" }
toml = "^0.5.9"
serde = "^0.9.15"