[package]
name = "buffered-lexer"
description = "A wrapper to logos' Lexer that adds extra functionalities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "^0.12.0"
log = "^0.4.17"
