[package]
name = "padma-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buffered-lexer = { path = "../buffered-lexer" }
swrs = { path = "../swrs" }

thiserror = "^1.0.38"
logos = "0.12.1"