[package]
name = "padma-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
padma-core = { path = "../padma-core" }
syn = "^1.0.107"
quote = "^1.0.23"
